### ISSUE TITLE
Encoding of the message body

### ISSUE THREAD

**Issue by pierreca** [grs/rhea#40]
Looks like [here](https://github.com/grs/rhea/blob/master/lib/message.js#L125) you encode the body as an AMQP value no matter what - is there a way for the user to force encoding to binary or sequence?

In node-amqp10 it looks like [the library tries to infer the type based on the type of the body](https://github.com/noodlefrenzy/node-amqp10/blob/836e3a8fd133654bb03cffa7b5dd7912da24a9f6/lib/types/message.js#L174) - i don't know if it is a good idea or not?

how do I force the body of a message to be encoded as binary data?

**Comment by grs** [comment]
To set the body to be a 'data' or 'amqp-sequence' section  instead of 'amqp-value', you need to use the special methods defined in rhea/lib/message.js (available as 'message' on the container object) , data_section() and sequence_section(). The former takes a buffer, the latter an array.

E.g.

var container = require('rhea');

var msg1 = {content_type:'text/plain',body:container.message.data_section(new Buffer('hello world!'))};
var msg2 = {body:container.message.sequence_section(['abc', 123, 'foo'])};

As a side point, you can send binary data in an amqp-value section (also lists). My personal opinion is that this is an area where the AMQP spec gives too many options. I went with using amqp-value by default, which doesn't limit the payload in anyway, with the ability to explicitly choose one of the other section types if desired.

**Comment by pierreca** [comment]
understood, thanks!!
